version: '3.9'

services: 
  proxy:
    container_name: proxy
    image: nginx:latest
    environment:
      TZ: Z
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
